### ISSUE TITLE
Problem ...

### ISSUE THREAD

**Issue by NorbiG74** [juancrescente/SMSHub#13]
Hi,

When I run your apk on my phone to send some data on my server in /var/log/nginx/access.log i have this:
5.173.28.92 - - [14/Sep/2021:10:07:56 +0200] "GET /gdzie/ HTTP/1.1" 200 31 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J120H Build/LMY47V)"
5.173.155.2 - - [14/Sep/2021:16:10:47 +0200] "GET /gdzie/aw HTTP/1.1" 404 143 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J120H Build/LMY47V) 

Error log empty.
In your documentation you wrote that this apk use POST method, but this log says something diffrent.

Regards

**Comment by juancresc** [comment]
https://github.com/juancrescente/SMSHub/blob/751f30318cf367ff640e23cbe4ea9918573cf278/app/src/main/java/com/ar/smshub/SendTask.kt#L21
