### ISSUE TITLE
Log not updating or not running

### ISSUE THREAD

**Issue by ampped101** [juancrescente/SMSHub#2]
I am trying to run this on a ONEPLUS6 with android 9. Does the text app have to be the stock version? The log is not updating as if it is not running at all. Is there another way to monitor it? 

I really appreciate the implementation.

**Comment by juancrescente** [comment]
hello, what do you mean with the text app and the stock version? are you able to run it in android studio?

**Comment by ampped101** [comment]
I use textra, but also just tried the default app. I am completely new to android programming but looking for this exact solution. Am downloading all of it now and will try to pick and poke my way around it. Thank you for this work.

**Comment by juancrescente** [comment]
take into consideration that you need a server side app to manage messages!

**Comment by ampped101** [comment]
This is the log error
2019-08-16 08:31:56.594 19715-19804/com.ar.smshub D/-->: Cannot connect to URL

This is the URL 
https://getmorechevelle.com/sms/send.php

**Comment by ampped101** [comment]
So I updated line 29 in SendTask.kt to 
Log.d("-->", "Cannot connect to URL" + settings.sendURL)
So that I could see if I had the URL correct..and then it sent.

Crashed on receiving a message back.

**Comment by juancrescente** [comment]
cooĺ! any logs when receiving?

**Comment by ampped101** [comment]
I have uninstalled and reinstalled. 

Send: Working
Status: Working
Receive: Working

Thank you so much for answering. Will dig into it more I am sure as I make a front end.

**Comment by ampped101** [comment]
Could you point my in the right direction to make something like this work

[ { "message":"Message 1", "number":"8473859106", "messageId":"1" }, {"message":"Message 2", "number":"8473859106", "messageId":"2" }, { "message":"Message 3", "number":"8473859106", "messageId":"3" } ]

Thanks

**Comment by juancrescente** [comment]
glad it worked!
you mean sending more than one at the time?
Maybe in SendTask.kt try to parse the json response as an array of SMS with Klaxon

**Comment by ampped101** [comment]
Thanks! Time to read and dig in!

**Comment by juancrescente** [comment]
:D
