### ISSUE TITLE
Not working in background

### ISSUE THREAD

**Issue by andynhoo** [juancrescente/SMSHub#5]
The app stops working when the phone locks or switches to another app and it stays in the background

**Comment by dmd2222** [comment]
Solved this problem?

**Comment by Artaud** [comment]
dontkillmyapp.com

**Comment by dmd2222** [comment]
But this does not solve the problem.

**Comment by Artaud** [comment]
Right, I didn't notice that the app doesn't post a foreground service notification. It definitely should do that to stay alive.
